- man/asciinema.1
Every well behaved unix program should have own man page. This is basic one heavily inspired by your README.md file and contributing page.
> Add basic man(1) page

- man/asciinema.1
Edit some details and add info for play and upload commands.
> Man page should correspond to current commands

- util/cfg.go
Currently the config path `$HOME/.asciinema/config` is hard-coded, which is not so cool for users who keep all their config stuff in `$HOME/.config` for a cleaner `HOME` and easier backup (following the [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html)). Therefore, I'm introducing an `ASCIINEMA_CONFIG` environment variable in this PR to let users keep their config files wherever they want. (Personally I would set it to `$HOME/.config/asciinema/config`.)
> Add environment variable ASCIINEMA_CONFIG_HOME for customizing path to the config dir

- api/api.go
Relevant issue: #121
This tiny PR gzips the body of the POST request before uploading it, and adds the appropriate `Accept-Encoding` header to the request. As far as I can tell, no change needs to be made on the Rails end, since `Net::HTTP` knows to automatically decompress gzipped requests if they contain the `Accept-Encoding: gzip` header.
I tested this by compiling locally and uploading [an asciicast](https://asciinema.org/a/5a4ro8drmyekusbrzbrt3n5ur) and it seemed to work, but if there's more I should do to ensure this is okay, let me know.
> Gzip data for upload

- .travis.yml
- asciinema/__init__.py
- asciinema/api.py
- asciinema/commands/auth.py
- asciinema/player.py
- asciinema/pty_recorder.py
- setup.py
- tests/config_test.py
No new functions, just coding edit coding style to pass with pep8 check. Except `E501 line too long`.
> respect PEP8 coding style

- setup.py
Repair tests broken by #179 and #181
> pep8: inlude modules on top of a file

- README.md
- asciinema/__main__.py
- asciinema/commands/play.py
- asciinema/config.py
- asciinema/player.py
- man/asciinema.1
> add --speed parameter to play command

- asciinema/pty_recorder.py
Properly write a recording file if asciinema is terminated with SIGHUP, SIGTERM, SIGQUIT.  This happens, for example, if the machine is rebooted during a recording session.
> Trap more signals than just SIGCHLD

- asciinema/asciicast.py
> Add fallback for `JSONDecodeError`

- README.md
- asciinema/__main__.py
- asciinema/asciicast/v2.py
- asciinema/commands/record.py
- asciinema/config.py
- tests/config_test.py
> Environment variable capture

- doc/asciicast-v2.md
> Document `theme` entry in asciicast v2

- README.md
- asciinema/__main__.py
- asciinema/commands/record.py
Closes https://github.com/asciinema/asciinema/issues/249
Add overwrite option to overwrite the recording file if it exists.
The overwrite flag overrides the append option.
> Add --overwrite option to rec

- .gitignore
- asciinema/commands/record.py
- prints "exit opened program when you're done" if command was specified, or  "press <ctrl-d> or type "exit" when you're done" otherwise
- add better .gitignore file from [github/gitignore](https://github.com/github/gitignore/blob/master/Python.gitignore) (+ old one). Added it because I needed to hide my .venv :(
- slight refactoring (sort import, wrap really long line)
this pull request will close issue #328
> Change "how to stop recording" info message

- CONTRIBUTING.md
- man/asciinema.1.md
Partially solves https://github.com/asciinema/asciinema-server/issues/385.
> Replace mentions of freenode with libera.chat

- README.md
* nit-pick in the README.md file.
* update to Ubuntu 20.04
> README: update version mentioned for base image

- asciinema/commands/record.py
Do not append if the file does not exit.
> Append Behavior

- asciinema/asciicast/raw.py
- asciinema/asciicast/v2.py
- asciinema/async_worker.py
- asciinema/file_writer.py
- asciinema/recorder.py
Automatically reopen named pipe (FIFO) and resume writing upon BrokenPipeError.
> Improved handling of named pipes (FIFO)

- asciinema/pty_.py
- tests/integration.sh
It was broken during pty module refactor.
This also adds integration test to prevent regression in this.
> Fix stdin recording

- Dockerfile
I just updated the Dockerfile to use Ubuntu 22.04 LTS.
> Update Dockerfile to Ubuntu 22.04 LTS

- asciinema/commands/record.py
- asciinema/file_writer.py
- asciinema/recorder.py
Checks for target dir presence, write permission, etc.
> File writing improvements

- asciinema/pty_.py
**asciinema(1)** currently **write(2)**s to pty master fd synchronously, which could be blocking if the internal pty input buffer became full; while the programs running under the pty may also be blocking on writing to pty slave fd, because the pty output buffer can also become full at same time. Once this happens, the entire terminal session hangs; the only way to get rid of it is to kill the asciinema processes via `SIGKILL`.
The following steps can be used to reproduce the bug:
* Start a terminal recording
* Run `cat` in the pseudo terminal that's being recorded
* Prepare large amount of text and put it in X11 primary selection (or clipboard if that's preferred); how about 2000 lines of `w` repeating 80 times for each line?
```sh
i=0; while [ $i -lt 2000 ]; do echo …
```
> Fix **write(2)** to pty master fd synchronously causing deadlock

- Cargo.lock
- Cargo.toml
- src/util.rs
No hard-coded server URL, requires explicit server URL as the second argument to `upload`:
```sh
asciinema upload demo.cast https://asciinema.org
```
> Rust - upload

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/main.rs
No hard-coded server URL, requires explicit server URL as the second argument to `upload`:
```sh
asciinema upload demo.cast https://asciinema.org
```
> New implementation of upload command

- Cargo.lock
- Cargo.toml
- src/pty.rs
- src/tty.rs
This fixes recording on macOS, where mio can't poll /dev/tty via kqueue.
Fixes #598
> Replace mio with select in the recorder, add signal handling

- build.rs
This will generate the following files:
```console
asciinema.1
asciinema-auth.1
asciinema-cat.1
asciinema-convert.1
asciinema-play.1
asciinema-rec.1
asciinema-stream.1
asciinema-upload.1
```
See https://github.com/asciinema/asciinema/issues/627#issuecomment-2106656577
> Generate subcommands man pages

- src/pty.rs
The pty master fd is closed twice, once when dropping OwnedFd in `fn exec` and once when dropping File constructed with unsafe code in `fn copy`.
This causes IO Safety violation[^1] and should be avoided. It becomes a crash in debug build[^2].
[^1]: https://github.com/rust-lang/rust/commit/1ba00d9cb2fcfef464b6a188fa3a7543c66eecaa
[^2]: https://github.com/zed-industries/zed/issues/12114
> fix: avoid closing pty master fd twice
