asciicast/player.go, commands/play.go, main.go, util/cfg.go, util/cfg_test.go
Take the -w option on playback, which reduces all intervals in the recorded
file to the specified number of seconds (or less)
=> Simple patch to enable max-wait for playback

asciicast/asciicast.go
This would be good for piping, for example:
`$ curl http://example.com/asciinema-recording.gz | gunzip | asciinema play -`
Never used Go before, but seems to work.
=> Support playing file from stdin

.travis.yml
http://docs.travis-ci.com/user/migrating-from-legacy/#Why-migrate-to-container-based-infrastructure%3F
=> Switch to modern Travis CI infrastructure

asciicast/player.go, asciicast/recorder.go, asciicast/stream.go, commands/play.go, commands/rec.go, commands/rec_test.go, main.go, util/cfg.go, util/cfg_test.go
Nothing sophisticated, just changed the type in all places. I'm not proficient in Go, so excuse me if I did something stupid. Possible improvements:
- indicate this change in the docs explicitly
- check that the input parameter is positive and print an error otherwise
=> Changed max-wait parameter type to float64

setup.py
Module `distutils` don't know options `install_requires` and
`entry_points`. The second one is important for creating `asciinema`
binary within $PATH.
This should "resolve" Issue #174.
=> setup: distutils can't create wrapper in $PATH

asciinema/config.py
This addresses #185, by adding a new fallback method of an environment variable named `ASCIINEMA_TOKEN` to store the user's API token so that sensitive information doesn't have to be kept in plaintext on disk.
=> adding support to loading API token from an environment variable

asciinema/asciicast/v2.py
This solves #216.
Example of secret leak:
asciinema rec -c 'export API_KEY=secret-stuff; ./script.sh'
The resulting asciicast would include `"command": "export API_KEY=secret-stuff; ./script.sh"`.
=> Don't save user command, to avoid leaking secrets

asciinema/urllib_http_adapter.py
> ### base64.encodestring(s)
> Deprecated alias of encodebytes().
> ***Deprecated since version 3.1.***
* https://docs.python.org/3/library/base64.html#base64.encodestring
=> Use `encodebytes` instead of `encodestring` (deprecated since Python 3.1)

doc/asciicast-v2.md
The v2 file format [example for `env`](https://github.com/asciinema/asciinema/blob/develop/doc/asciicast-v2.md#env) has the `TERM` and `SHELL` variables swapped:
```json
"env": {
"SHELL": "xterm-256color",
"TERM": "/bin/bash"
}
```
This commit fixes that by swapping them back.
=> Swap TERM and SHELL in v2 file format example

asciinema/asciicast/v2.py
On platforms (Android) where multiprocessing is not supported we now use threads instead. Fixes #271.
=> Add a fallback when multiprocessing is unsupported

man/Makefile, man/asciinema.1.md
My changes include:
1. *`asciinema.1.md`* source file for manual page is extended by a few pieces.
1. *`Makefile`* command for Pandoc to generate the manual page is modified to include version+date of manual page generation.
This PR does NOT include:
+ A freshly generated *`asciinema.1`* manual page -- this has to be run on your side should you accept (parts of) my suggested additions.
Note, I have not included an actual *`asciinema.1`* manual page due to the fact that my local Pandoc is still stuck with v.1.19.2.4 whereas you seem to be using v2.1.1 already, and I didn't want to push too many minor backward changes like with 'smart quotes' etc.
=> Manual page additions

asciinema/recorder.py
A simple fix to the ASCIINEMA_REC issue: [ASCIINEMA_REC is not set (#372)](https://github.com/asciinema/asciinema/issues/372).
To reproduce:
$ asciinema rec -c 'echo "ASCIINEMA_REC=$ASCIINEMA_REC"'
ASCIINEMA_REC=
Expected behavior:
$ asciinema rec -c 'echo "ASCIINEMA_REC=$ASCIINEMA_REC"'
ASCIINEMA_REC=1
Thanks for all your hard work!
=> Bugfix: Ensure ASCIINEMA_REC set on record (#372).

asciinema/__main__.py
On HP-UX UTF-8 aware locales end with '.utf8'.
=> Fix codeset detection on HP-UX

asciinema/commands/cat.py, asciinema/term.py
If the asciicast contains escape sequence queries like "CSI 6 n", the terminal will both echo and input its responses.  Use the raw() context manager that we already have to attempt to consume this "input."
There is, unfortunately, no way of finding out exactly when the terminal has finished its answerbacks.  This patch adds a 50ms wait, which should be overkill for a local terminal (in my tests, 3ms was usually enough).  For a remote terminal, this number becomes harder to estimate.
Technically this only needs to be done if whatever we're writing to isatty(), but keep it simple for now.
=> Consume terminal answerbacks in asciinema cat

README.md, asciinema/commands/play.py, asciinema/commands/record.py, asciinema/config.py, asciinema/player.py, asciinema/pty.py, asciinema/recorder.py
Fixes #343.
This implements configurable hotkeys for `rec` and `play` commands.
Example config file:
```ini
[record]
; Define hotkey for pausing recording (suspending capture of output),
; default: C-\
pause_key = C-p
; Define hotkey prefix key - when defined other recording hotkeys must
; be preceeded by it, default: no prefix
prefix_key = C-a
[play]
; Define hotkey for pausing/resuming playback,
; default: space
pause_key = p
; Define hotkey for stepping through playback, a frame at a time,
; default: . (dot key)
step_key = ]
```
=> Configurable key bindings (hotkeys) for rec and play commands

asciinema/term.py
tput is part of ncurses, which may not be installed.
It still falls back to tput for older Python versions (this was
introduced in 3.3) or for platforms which may not support it.
Fixes #418
=> Use os.get_terminal_size()

README.md
I'm suggesting some improvements to the installation instructions, as discussed in https://github.com/asciinema/asciinema/issues/116#issuecomment-983691890 — see this comment for full rationale.
Basically we should never tell users to pip install with `sudo`, and also it would be helpful to recommend using `pipx` for a more reliable installation if the user has it.
Please note: I think the web site should also be updated accordingly:
https://asciinema.org/docs/installation
=> Recommend pipx installation, remove sudo

README.md, asciinema/__main__.py, asciinema/commands/record.py, asciinema/pty_.py, asciinema/recorder.py, asciinema/term.py, man/asciinema.1.md, tests/pty_test.py
This adds `--cols <n>` / `--rows <n>` options to `rec` command. This disables
autodection of terminal size, and reports fake fixed number of columns/rows to
the recorded process.
=> Option to override cols/rows of the recorded process

README.md, asciinema/__main__.py, asciinema/asciicast/events.py, asciinema/asciicast/v1.py, asciinema/asciicast/v2.py, asciinema/commands/cat.py, asciinema/commands/play.py, asciinema/player.py
Allows selecting stream to replay, either output (`o`) or input (`i`). Defaults to output.
=> Add `--stream` option to `play` command

README.md, asciinema/__main__.py, asciinema/asciicast/v1.py, asciinema/asciicast/v2.py, asciinema/commands/play.py, asciinema/player.py
Implements playback output in asciicast format, allowing it to be streamed elsewhere.
=> Add `--out-fmt` option to `play` command

asciinema/async_worker.py, asciinema/pty_.py, asciinema/recorder.py
This improves input handling for `rec` command:
- we now always read keys from stdin only, while previously we read from both stdin and directly from tty, which was problematic when piping
- keyboard interrupt is now handled in a more graceful way
=> Fix piping of input into `rec` command

README.md, asciinema/__main__.py, asciinema/asciicast/raw.py, asciinema/asciicast/v2.py, asciinema/commands/play.py, asciinema/commands/record.py, asciinema/config.py, asciinema/player.py, asciinema/pty_.py, asciinema/recorder.py, doc/asciicast-v2.md, tests/integration.sh
This one adds breakpoints - locations in the recording which allow the player to auto-pause when one is encountered.
A breakpoint is new `"b"` event type in asciicast stream, with optional annotation (comment) as event data.
To add a breakpoint during recording session press a hotkey (specified in config file as `add_breakpoint_key`).
To add breakpoints to existing recording you add `"b"` events like this:
```
...
[1.000000, "o", "some text"]
[2.500000, "b", ""]
[3.750000, "o", "more text"]
[4.500000, "b", "chapter 5"]
...
```
=> Breakpoints

asciinema/__main__.py, asciinema/commands/cat.py
Despite its name, the `cat` subcommand accepts only 1 input file, and can't really be used to concatenate multiple files.
Making it a true `cat` would be useful at least to myself.
=> Make `cat` subcommand be capable to actually concatenate multiple recordings

asciinema/asciicast/raw.py, asciinema/asciicast/v2.py, asciinema/pty_.py, asciinema/recorder.py, doc/asciicast-v2.md
This saves new resize event, `r`, which can be used by the player to resize its view.
Fixes #140
=> Terminal resize capture

asciinema/pty_.py
After #556, **asciinema(1)** will **write(2)** the pty master fd only when **select(2)** indicated that it is ready to write; however when using the fixed version one day, I encountered another issue which caused **asciinema(1)** to silently exit without any error message.
So far I can only reproduce this issue on a particular machine, here's my troubleshooting steps:
* I found that some try-except codes hide the error messages completely, so I temporarily removed such codes to show the full error and stacktrace:
```diff
diff --git a/asciinema/commands/record.py b/asciinema/commands/record.py
index e60002d..a11bfe7 100644
--- a/asciinema/commands/record.py
+++ b/asciinema/commands/record.py
@@ -139,9 +139,6 @@ class RecordCommand(Command):  # pylint: disable=too-many-instance-attributes …
```
=> Ignore BlockingIOError when trying to write pty master fd

asciinema/pty_.py
Fix for #369.
asciinema parent process doesn't set handler for SIGPIPE, which by default sets SIG_IGN for this signal in a child process. This explicitly sets the handler in the child process to SIG_DFL.
This is something script and mosh do right before exec-ing the command in a child process:
script - https://github.com/util-linux/util-linux/blob/f3fd64111c28de1ecd47f7cd519120ffa531800d/term-utils/script.c#L987
mosh - https://github.com/mobile-shell/mosh/blob/1105d481bb9143dad43adf768f58da7b029fd39c/src/frontend/mosh-server.cc#L540-L546
Many thanks to @Low-power for figuring this out :clap:
=> Re-enable default signal handler for SIGPIPE in child process

asciinema/commands/command.py, asciinema/commands/record.py
This changes the prompt for upload from simply accepting `<enter>` key as upload confirmation to requiring explicitly typing `u<enter>`. Also, lets saving locally in tmp directory (what was previously achieved with `<ctrl-c>`, and adds discard option too.
```
$ asciinema rec
asciinema: recording asciicast to /tmp/tmpo8_612f8-ascii.cast
asciinema: press <ctrl-d> or type "exit" when you're done
$ echo hello
hello
$ exit 
asciinema: recording finished
(s)ave locally, (u)pload to asciinema.org, (d)iscard
[s,u,d]? _
```
If none of `s`, `u`, `d` are entered (which includes just hitting enter) then the prompt is displayed again, until valid choice is made. `<ctrl-c>` works as it did in previous versions, which is equivalent to `s` (save).
Discussed in:
- …
=> Require explicit upload choice when recording without file arg

src/lib.rs, src/main.rs
No hard-coded server URL, requires explicit server URL as the first argument to `auth`:
```sh
asciinema auth https://asciinema.org
```
=> New implementation of the auth command

src/cmd/cat.rs, src/cmd/rec.rs, src/format.rs, src/format/asciicast.rs, src/format/raw.rs, src/recorder.rs
In 3.0 `cat`'s primary function will be to concatenate multiple asciicast files, adjusting the timestamps accordingly, printing the output asciicast file to stdout.
=> New impl of `cat` command

Cargo.lock, Cargo.toml, src/cmd/rec.rs, src/output/mod.rs, src/output/txt.rs, src/recorder.rs
This adds ability to produce a pure text log of a session by recording with `--format txt` option or passing a filename with `.txt` extension.
=> Implement text output for `rec` command

src/asciicast/v2.rs, src/cmd/convert.rs, src/cmd/mod.rs, src/encoder/asciicast.rs, src/encoder/mod.rs, src/main.rs
```
$ asciinema convert -h
Convert a recording into another format
Usage: asciinema convert [OPTIONS] <INPUT_FILENAME_OR_URL> <OUTPUT_FILENAME>
Arguments:
<INPUT_FILENAME_OR_URL>
<OUTPUT_FILENAME>
Options:
-f, --format <FORMAT>  Output file format [default: asciicast] [possible values: asciicast, raw, txt]
--overwrite        Overwrite target file if it already exists
```
This provides conversion from asciicast (v1 and v2) into asciicast v2, raw output, or plain text log.
When output filename has `.txt` extension then text output is assumed (unless `--format` option given).
Examples:
```
asciinema convert demo.json demo.cast
asciinema convert demo.cast demo.txt 
asciinema convert demo.cast demo.raw -f raw 
asciinema convert https://asciinema.org/a/Ry4cnZr5VHFIBRbmk9XBld5To demo.txt 
```
=> Add `convert` command

Cargo.lock, Cargo.toml, src/cmd/stream.rs, src/config.rs, src/streamer/mod.rs, src/streamer/server.rs, src/streamer/session.rs
This adds logging for the streamer (`asciinema stream` command).
Disabled by default.
Can be enabled by specifying a log file via `--log-file` option to `stream` command:
```
asciinema stream --log-file stream.log
```
Alternatively, it can be set permanently in the config file (`~/.config/asciinema/config.toml`):
```toml
[cmd.stream]
log_file = "/tmp/asciinema-stream.log"
```
=> Logging for the `stream` command

Cargo.lock, Cargo.toml, src/asciicast.rs, src/asciicast/v1.rs, src/asciicast/v2.rs, src/cmd/rec.rs, src/encoder/asciicast.rs, src/tty.rs, tests/casts/full.cast, tests/casts/minimal.cast
This uses OSC sequence to query the colors from the terminal, and saves them as a theme in asciicast v2 header
(https://docs.asciinema.org/manual/asciicast/v2/#theme).
=> Capture terminal color palette

Cargo.lock, Cargo.toml, src/cmd/mod.rs, src/cmd/rec.rs, src/cmd/stream.rs, src/streamer/forwarder.rs, src/streamer/mod.rs, src/streamer/server.rs, src/streamer/session.rs, src/util.rs
This implements stream forwarding (to asciinema server) for `asciinema stream` command.
- `asciinema stream -r` - relay the stream to user's default server stream
- `asciinema stream -r <ID>` - relay the stream to user's specific server stream
- `asciinema stream -r -s` - both relay and serve the stream locally
---
TODO:
=> Stream forwarder

Cargo.toml
I've been using the latest version of `scraper` on Fedora Linux and it's been working fine. We can update it to 0.19.0.
=> Bump scraper version from 0.15.0 to 0.19.0

src/asciicast/v2.rs
=> fix: manual `ToString` implementation for `RGB8`

Cargo.lock, Cargo.toml
Add add `rustls-tls-native-roots` feature to reqwest so that the binary can use CA certificates from OS's keystore.
It solves the problem that we cannot upload cast to a self-hosted server with a private CA certificate.
=> fix(reqwest): use rustls-tls-native-roots to profite OS level custom CA certs

src/pty.rs
We could use libc::EIO to improve readability of the code.
=> Avoid hardcoding 5 for errno EIO

src/pty.rs
Previously the code uses unsafe kill from libc and on the first look it appears that it forgets to check the result.
I think you mean to ignore the errors that might occur when killing the child, right? This commit makes the intent more clear with less unsafe code.
=> Use safe kill from nix crate

src/cli.rs, src/cmd/play.rs, src/player.rs
The new `-r` or `--resize` option causes asciinema to send `CSI 8 ; <width> ; <height> t` for `r` commands in the Asciicast. This causes the terminal window to resize as it did during the recording. This commit also sets the initial size. Doing so causes recordings of interactive programs to render properly.
Resizing is off by default for backward compatibility.
I see this [was discussed](https://github.com/asciinema/asciinema/issues/198) previously but as far as I can tell it was closed without being implemented.
=> Add support for play -r.

src/api.rs
The unauthenticated streaming attempt prints out an erroneous message:
> "this CLI hasn't been authenticated with {server_hostname} - run • `ascinema auth` first"
=> fix: typo in 'asciinema' in the authentication message

src/cmd/session.rs
As discussed in #680 this adds some additional information to the output generated after asciinema exits.
Feel free to reject this PR if this do not want to add or update this part of the code.
But if you like the general idea but this needs changes, let me know.
=> Add filename of cast file to session end output
